// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyWebApi.Context;

namespace Palamut.Web.Api.Migrations
{
    [DbContext(typeof(PalamutContext))]
    partial class PalamutContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MyWebApi.Model.Alici", b =>
                {
                    b.Property<int>("AliciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AliciName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AliciTelNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AliciID");

                    b.ToTable("Alicilar");
                });

            modelBuilder.Entity("MyWebApi.Model.Satici", b =>
                {
                    b.Property<int>("SaticiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaticiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaticiTelNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SaticiID");

                    b.ToTable("Saticilar");
                });

            modelBuilder.Entity("MyWebApi.Model.Siparis", b =>
                {
                    b.Property<int>("SiparisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AliciID")
                        .HasColumnType("int");

                    b.Property<int>("SaticiID")
                        .HasColumnType("int");

                    b.Property<float>("ToplamFiyat")
                        .HasColumnType("real");

                    b.HasKey("SiparisID");

                    b.HasIndex("AliciID");

                    b.HasIndex("SaticiID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("MyWebApi.Model.Urun", b =>
                {
                    b.Property<int>("UrunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Stok")
                        .HasColumnType("int");

                    b.Property<float>("UrunFiyat")
                        .HasColumnType("real");

                    b.Property<string>("UrunName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunID");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("MyWebApi.Model.Siparis", b =>
                {
                    b.HasOne("MyWebApi.Model.Alici", "Alici")
                        .WithMany()
                        .HasForeignKey("AliciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyWebApi.Model.Satici", "Satici")
                        .WithMany()
                        .HasForeignKey("SaticiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alici");

                    b.Navigation("Satici");
                });
#pragma warning restore 612, 618
        }
    }
}
